### ISSUE TITLE
Best practices TODO

### ISSUE THREAD

**Issue by anandbaburajan** [FOSS-Cell-GECPKD/P2P-file-transfer#4]
### Code
* [x] Proper readable and maintable code with consistent spacing and indentation
* [x] Functions follow the "Do One Thing" rule (single-responsibility)
* [x] Followed DRY (Don’t Repeat Yourself)
* [x] Added comments wherever required
* [x] Proper naming conventions
* [x] Avoided deep nesting

### Readme
* [x] Badges (similar to the Gitter badge. You can maybe use: https://shields.io/)
* [x] Description (why this project exists)
* [x] Features (working of the project)
* [x] Setup (Quick start instructions with how to download and use your project)
* [x] Contributing (How can others contribute?)
* [x] License ("This project is licensed under the <your license>")

### Tests
* [ ] Wrote tests

**Comment by anandbaburajan** [comment]
@sankarvinayak and @MUHAMMEDRIZALKE, great work and thanks for contributing! You're just left with one item in your TODO! Also, do you wish to rename your project and repo? Also, can you update the instructions in you readme? Running `python peer.py` doesn't seem to be working.

Also, there's a small typo in your readme. Please replace 'Discussions about P2P-file-transfer is placed on our Gitter Chat Anybody is welcome to join these conversations.' with: 'Discussions about P2P-file-transfer take place on our Gitter Chat. Anyone is welcome to join the conversations.'

Also, it would be really great if your functions had a docstring.

**Comment by anandbaburajan** [comment]
I'm trying to run your project but `python peer.py` command isn't working. Can you please look into it? Thanks!
